[package]
name = "gitgc"
version = "0.1.0"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]

[dependencies]
walkdir = "2.0"
humansize = "1.0"
git2 = "0.7"


[profile.release]
lto = true
opt-level=3
codegen-units=1
