[package]
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
edition = "2018"
name = "gitgc"
version = "0.1.0"

[dependencies]
git2 = "0.13"
humansize = "1.0"
walkdir = "2.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
